### ISSUE TITLE
No .NET 4.5 support in NuGet package

### ISSUE THREAD

**Issue by ranec** [onovotny/Zeroconf#10]
I tried a ZeroConf search in the nuget library in a solution that just has projects targeting .NET 4.5 and the results came up empty.

I went the manual route and tried "Install-Package ZeroConf" from the console and got the following:
>Install-Package : Could not install package 'Zeroconf 2.3.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the 
>package does not contain any assembly references or content 

Is there another route to get the .NET 4.5 component outside of compiling our own?  Or is this an issue you are able to resolve by rebuilding the nuget package with a .NET 4.5 target (I admit i'm ignorant to the ways of nuget package building)?

**Comment by onovotny** [comment]
Hi @ranec,

From the error message it looks like your target project is set to .NET 4, not 4.5. The NuGet package contains support for .NET 4.5 and higher.

**Comment by ranec** [comment]
Wow, that's just a complete fail on my part.  Thanks for the response.

**Comment by onovotny** [comment]
no worries, let me know if you run into any issues!
