### ISSUE TITLE
Compatibility with Windows 10 DNS-SD

### ISSUE THREAD

**Issue by matthew-a-thomas** [onovotny/Zeroconf#101]
Windows 10 provides DNS-SD support to UWP apps. Using this code you can register a DNS-SD service: https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd

However, [there is a bug with their APIs](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/34826236-dns-sd-registration-does-not-respond-to-queries-wi) where Windows will not respond to DNS queries having the class set to "ANY", but will only respond for queries having the class set to "IN". Windows behaves differently than Bonjour. Bonjour will respond to queries for both "ANY" and for "IN".

This Zeroconf library issues queries with a class of "ANY". Therefore it cannot find services registered with Windows 10's APIs.

Also, this Zeroconf library is different than Bonjour. Bonjour issues queries with a class of "IN".

So I propose that Zeroconf's queries be issued with a class of "IN".

**Comment by matthew-a-thomas** [comment]
bump

**Comment by Holo-Krzysztof** [comment]
Is this still an issue? I haven't tried it out myself yet, but that'd be pretty limiting to my use case.

**Comment by matthew-a-thomas** [comment]
@Holo-Krzysztof I assume so. I've kind of moved on, but hopefully someone from the Zeroconf team will pick this up

**Comment by onovotny** [comment]
This has been fixed in 3.3.
