### ISSUE TITLE
ResolverListener doesn't refresh counter of ToRemove if response is successfull again.

### ISSUE THREAD

**Issue by niklasgh** [onovotny/Zeroconf#105]
A service is marked as lost even if it responds to a query ping before the last. The count that is compared to pingsUntilRemoved isn't refreshed if it responds again, the count just isn't increased. So if over its lifetime it doesn't respond pingsUntilRemoved-times to a query it gets marked as lost. 

My suggestion would be that a host only gets marked as lost if it doesn't respond to pings n-times  successively and not in it's lifetime, or at least give that as a configuration option.

**Comment by spudwebb** [comment]
I ran into the same issue, and created a PR to fix it
