### ISSUE TITLE
Can't export to linux-arm

### ISSUE THREAD

**Issue by dviljoen** [onovotny/Zeroconf#107]
Trying to build a zeroconf enabled app for Raspberry Pi.  Using latest sdk gives this error on Visual Studio during publish:

Severity	Code	Description	Project	File	Line	Suppression State
Error		NETSDK1061: The project was restored using Microsoft.NETCore.App version 2.1.4, but with current settings, version 2.1.0 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore. For more information, see https://aka.ms/dotnet-runtime-patch-selection.	ConsoleCoreSandbox	d:\projects\ConsoleCoreSandbox\ConsoleCoreSandbox\ConsoleCoreSandbox.csproj	1	

When I went into my project properties to downgrade to 2.1.0 so see if that would clear it up I'm seeing this (which appears to be a VS or Nuget bug).
![image](https://user-images.githubusercontent.com/849415/46290343-32cb3080-c551-11e8-8ee9-a753ddaa57c8.png)

**Comment by dviljoen** [comment]
Thoughts?

**Comment by dviljoen** [comment]
When installing Zeroconf nuget package I get this. 
![image](https://user-images.githubusercontent.com/849415/46291382-ea614200-c553-11e8-8ace-3be0f5ba2eb8.png)

**Comment by dviljoen** [comment]
I added the correct RuntimeFrameworkVersion to my project file.  LIke this:
  <PropertyGroup>
    <RuntimeFrameworkVersion>2.1.0</RuntimeFrameworkVersion>    
  </PropertyGroup>

This cleared up this publish error.

**Comment by onovotny** [comment]
This looks like a VS/tooling but, not Zeroconf. I would use the "Report a problem" wizard in the upper-right of VS and reproduce the issue there.
