### ISSUE TITLE
Discovery through hotspot

### ISSUE THREAD

**Issue by ranec** [onovotny/Zeroconf#11]
I'm having trouble discovering zeroconf services that hosts connected to the iPad using its hotspot are serving.

Here's the scenario:
1) iPad is in hotspot mode
2) device with zeroconf server is connected to the iPad personal hotspot using wifi (to simplify testing i've been using xamarin's build host as the zeroconf server since our own host requires a separate piece of hardware)
3) a call is made to BrowseDomainsAsync but always shows up empty

I tested the same code with both the iPad and the device connected to the same wifi network and had no trouble discovering the service being offered, but if I go into hotspot mode it doesn't appear to be broadcasting the request to the internal wifi network, just the cellular network, so my app never finds the hosted service.

Any clue on this?  Would you expect this to work?  I briefly read through the code and it appears you're broadcasting such that it *should* go to every network.  Maybe a modification can be made (on my end if necessary) to allow me to specify the netmask or some portion of the IP range to broadcast to (e.g. 172.20.10.*)?

**Comment by ranec** [comment]
Too add some info to this I wrote an iOS app that pumped out some information from the GetAllNetworkInterfaces() call and when there is a personal hotspot enabled the bridge100 interface shows up and appears to be the internal network interface (with IP 172.20.10.1).

Maybe I end up implementing "GetBestInterface" for iOS and pick that interface if it exists, otherwise pick the default?  I'm not sure if the index you get back from the interfaces call matches what you're passing in to the SetSocketOption for MulticastInterface or if I'd have to translate the index somehow.  You're just giving it zero and I don't get zero in the interfaces call so I assume zero tells it to pick a default or the "best" as far as it knows, or there is a mismatch with the indices.

**Comment by onovotny** [comment]
Honestly, I'm not sure how iOS/mono picks the best interface in that scenario. It is using a multicast transmit/receive, so it does have to bind to a specified interface; it doesn't use all of them at once.

If you write code to do what you need, I'd be happy to take a PR.

**Comment by ranec** [comment]
We ended up just creating an interface for interaction with Zeroconf and implementing an iOS specific class using the iOS bonjour libraries.

On Jun 8, 2015 7:25 AM, Oren Novotny <notifications@github.com> wrote:

Honestly, I'm not sure how iOS/mono picks the best interface in that scenario. It is using a multicast transmit/receive, so it does have to bind to a specified interface; it doesn't use all of them at once.

If you write code to do what you need, I'd be happy to take a PR.

**Comment by onovotny** [comment]
Can you please retry using the latest versions? There were some changes to the code to send over every interface and this may be resolved.

**Comment by onovotny** [comment]
Closing for now as we should be scanning all interfaces now. Please re-open if this is still an issue.

**Comment by amongster** [comment]
I have noticed this issue as well.   My setup is similar to what the original post identified.  I am using the personal hotspot on iphone XS with iOS 13.  Code written with Xamarin.iOS.  Everything works great under other circumstances (different wifi network/host).  I'm new to github, so I'm not sure if this is how I should report this or not.  I know this is an old thread and that is somewhat frowned upon.
