### ISSUE TITLE
What is README.md talking about?

### ISSUE THREAD

**Issue by ksze** [onovotny/Zeroconf#13]
From README.md:
> The core logic is implemented as a PCL, but due to networking APIs being platform-specific, a platform-specific helper library is required. Just make sure that you also install the NuGet to your main app and you'll be all set.

What is it talking about?

I know PCL stands for "Portable Class Library", but I don't think everybody knows it.

And what "platform-specific helper library"? Can you give an example? Do you mean something like Apple's Bonjour SDK for Windows, if I want to use this Zeroconf in a .NET 4.5 application on Windows 8.1?

**Comment by onovotny** [comment]
There's really no magic to it. It's simply saying that you must reference the nuget project by your app as well as any portable libraries that might use it.

Platform-specific helper library is just saying that the library has platform specific code and is implemented slightly differently on each platform as a result. This is an implementation detail though and should not matter if you add the NuGet package to all of your projects.

The library is supported on .NET 4.5, Windows Phone 8, Windows 8.1, Xamarin iOS and Android. Basically every platform .NET currently runs on.
