### ISSUE TITLE
Zeroconf can filter out mDNS responses from devices

### ISSUE THREAD

**Issue by peteradleff** [onovotny/Zeroconf#143]
We have seen an issue when scanning our network where a network device responds with A RECORDs in a different order then other devices. The source IP Address does not match the **first** A RECORD in either Answer or Additional Records. The source IP address is found in second or third A RECORD. 
This causes the ResolveInternals callback method (Converter) to filter out devices due to usage of FirstOrDefault on line 53 in ZeroconfResolver.cs. Should the responder always send the source IP address as the first record?

                void Converter(IPAddress address, byte[] buffer)
                {
                    var resp = new Response(buffer);
                    var firstPtr = resp.RecordsPTR.FirstOrDefault();
                    var name = firstPtr?.PTRDNAME.Split('.')[0] ?? string.Empty;
                    var addrString = address.ToString();

                    Debug.WriteLine($"IP: {addrString}, {(string.IsNullOrEmpty(name) ? string.Empty : $"Name: {name}, ")}Bytes: {buffer.Length}, IsResponse: {resp.header.QR}");

                    if (resp.header.QR)
                    {
                        // see if the IP is the same as the A to filter out dups that might echo from other interfaces

                        var aRec = resp.RecordsA.FirstOrDefault();
                        var additionalARec = resp.Additionals.FirstOrDefault(arr => arr.Type == Type.A)?.RECORD as RecordA;

                        // if we have an aRec or additionalARec, check those
                        bool? matches = null;
                        if (aRec != null || additionalARec != null)
                        {
                            matches = string.Equals(aRec?.Address, addrString, StringComparison.OrdinalIgnoreCase) ||
                                      string.Equals(additionalARec?.Address, addrString, StringComparison.OrdinalIgnoreCase);
                        }
                        
                        if (matches ?? true)
                        {
                            var key = $"{addrString}{(string.IsNullOrEmpty(name) ? "" : $": {name}")}";
                            lock (dict)
                            {
                                dict[key] = resp;
                            }

                            callback?.Invoke(key, resp);
                        }
                    }
                }

**Comment by onovotny** [comment]
This should be resolved as part of #145
