### ISSUE TITLE
TXT Records with a BAD length cause "Out of Memory" Exception in NetFx library

### ISSUE THREAD

**Issue by ekwus** [onovotny/Zeroconf#18]
Hi

I've been tracking down out of memory exceptions when using your library. It turns out they are due to a bad TXT record RDLENGTH field from a device on my network (it is serialising the ushort in Little Endian format which gives us a length of 11008 instead of 43.

Aside from the root of the cause being the bad device, the ReadByte() and ReadString() methods in RecordReader.cs continue to create StringBuilders due to the code in RecordTXT constructor

    public RecordTXT(RecordReader rr, int Length)
    {
        int pos = rr.Position; // This is initially 147 in my case, with m_data[190]
	TXT = new List<string>();
        while ((rr.Position - pos) < Length)
        TXT.Add(rr.ReadString());
    }

    (rr.Position - pos) == 190 - 147 == 43

The while loop test equals 43 and this is never more than 11008, which results in Out of Memory.

Please let us know if you would like me to do any further testing? I can also work on a fix, but my testing would be limited to the .NET4.5 framework only.

Cheers

Dave

**Comment by onovotny** [comment]
Sure, I'd be happy to have a fix. It is true that the servers should "do the right thing," but being strict like that doesn't help anyone get what they really want -- so I have no issue with libraries being more "tolerant"  and working around issues.

If you have a good fix, I'd be happy to take it.

**Comment by ekwus** [comment]
Hey

Yes the more resilient the better! I've made a really simple fix what break out of the ReadString while loop if the reader position reaches the end of the data. This stops the out of memory, but doesn't recover for the endian error - not sure if that would be possible.

I think I have made a pull request but I'm not that familiar with them so I may not have :-)

Cheers

Dave
