### ISSUE TITLE
PCL Compatibilty

### ISSUE THREAD

**Issue by Sparksteam** [onovotny/Zeroconf#24]
Installing this nuget package in a Visual Studio 2015, PCL project which targets Windows 10, Xamarin.Android, and Xamarin.iOS fails with the following error. Shouldn't I be able to do this?

Error		Could not install package 'Zeroconf 2.3.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

Thanks

**Comment by onovotny** [comment]
Okay, so here's the issue... this library only supports Win 8.1+ but Profile7 is Win8. The portable- folder in the Nuspec lists win81 but that's causing the issue.

What I can do at this point is to change the win81 in the nuspec to win8. That'll fix the PCL issue but it does leave open the possibility that someone tries to use this in a Win8 project where it'll fail.

That said, I don't think there are too many Win8 projects anymore...they should be at least 8.1 now.

**Comment by Sparksteam** [comment]
Yeah, I think the Win 8 store has been “closed” for a while. So I think it would be pretty safe to make the change and just document it on the Zeroconf project page, just to be safe.

Can you add this change to the 2.3.4 publish?

**Comment by onovotny** [comment]
yes, already checked in. the latest package on the appveyor ci feed has it already.

**Comment by Sparksteam** [comment]
Ahhh… I see it now. I’ll give it a spin.

 

Thanks Oren.

**Comment by onovotny** [comment]
closing for now as this will be in 2.4
