### ISSUE TITLE
Extending the Interface

### ISSUE THREAD

**Issue by Sparksteam** [onovotny/Zeroconf#26]
In PR #25, I've extended the interface a little more to provide a scan-in-progress status, throw an exception if a start scan is attempted while scanning is in progress, added a mechanism to know when scanning is complete via the callback, and also tested the Cancel scan mechanism. Please consider for incorporation into the main. Thanks.

**Comment by onovotny** [comment]
Hi @Sparksteam, question for you -- Why is a notification mechanism from the callback needed? Can't an app know when it's complete by using the returned Task? What's the scenario?

**Comment by Sparksteam** [comment]
The notification mechanism makes more sense when the scan is started asynchronously using the callback mechanism.

**Comment by Sparksteam** [comment]
BTW, I just committed the fixes for the missing XML comment warnings into my branch.

**Comment by Sparksteam** [comment]
Hi Oren. Should I be able to build the Zeroconf (portable) PCL from my branch and consume it in a Universal App? When I attempt to do this, the exception in here gets thrown.

        private static INetworkInterface LoadPlatformNetworkInterface()
        {
#if PCL
            throw new NotSupportedException("This PCL assembly must not be used at runtime. Make sure to add the Zeroconf Nuget reference to your main project.");
#else
            return new NetworkInterface();
#endif
        }

Can you tell me what I'm missing or doing wrong, and let me know how I can make this work?

Thanks.

**Comment by Sparksteam** [comment]
Ok Oren, I ran nuget.exe against the Zeroconf.nuspec file and created a .nupkg. But now when I try to install that package, I get this.

Zeroconf 2.3.5 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
Zeroconf 2.3.5 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
Zeroconf 2.3.5 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
Zeroconf 2.3.5 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
Zeroconf 2.3.5 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Zeroconf 2.3.5 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
Zeroconf 2.3.5 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore failed for 'Zerocnf_PCL_Test'.
Package restore failed. Rolling back package changes for 'Zerocnf_PCL_Test'.
========== Finished ==========

**Comment by Sparksteam** [comment]
Ok Oren, I was able to create a nuget package from my branch that is installable. I had to use your latest Zeroconf.nuspec file. Then I ran into a problem where the ZeroconfResolver static methods didn't recognize the additional "bestInterface" argument. I resolved that by bumping the nuget package version to 2.4.1. I'm not sure where the version checking is happening since I'm referencing a local nuget package. But anyway, I was able to build a simple app that can invoke the ZeroconfResolver methods no problem. But the way our production app is architected is as follows.

Main App (Universal)
   --> Class Library A (Universal)
      --> Class Library B (Universal)
          --> Zeroconf (PCL)

In this implementation, the call to ZeroconfResolver.ResolveAsync() throws this exception.

This PCL assembly must not be used at runtime. Make sure to add the Zeroconf Nuget reference to your main project.

I have installed the Zeroconf nuget package  in the Main app as well as the 2 Universal Class Libraries.

Is what I'm trying to do workable? If so, what do I need to do to get around this exception?

Thanks.

**Comment by Sparksteam** [comment]
Actually our architecture is this way.

Main App (Universal)
 --> Class Library A (Universal)
 ----> Class Library B (Universal)
 ------> Class Library (Portable)
 --------> Zeroconf (PCL)

**Comment by Sparksteam** [comment]
Never mind Oren, I did a clean rebuild of our solution and the exception is no longer thrown. Sorry for the email flurry.

**Comment by Sparksteam** [comment]
Hey Oren - did you get this reply?

Sorry Oren, what does “Rx” mean?

There’s certainly many ways to skin this cat. I tried to implement what I needed without further perturbation the of the ResolveAsync(),  BrowseDomainsAsync() and callback method signatures, but I hear what you’re saying. Besides using the IObservable, event subscription pattern, here a couple of more options.

1.	Expose a couple of events to which delegates can be assigned.
2.	Add an EventType argument to the existing callback signature.

What do you think?

**Comment by onovotny** [comment]
Sorry, it's been a very busy couple of weeks. Rx is the Reactive Extensions -- probably the "easiest" way to implement IObservable. 

In general I'm not a fan of using events for streams of things. In reality the callback "should" have probably been an IObservable anyway as this very closely translates to a stream of results.

My thoughts are that adding 
` IObservable<Tuple<string, string>> Browse(...)` and `IObservable<IZeroconfHost> Resolve(...)` is the best option.

**Comment by Sparksteam** [comment]
No worries Oren. I just wasn't sure my direct replies to your emails were actually getting to you. I'm ok with whatever way you think. I just need the functionality. Were you going to implement the IObservable pattern, or should I? I'm pretty busy myself with converting a fairly large codebase to cross-platform components. But just let me know what you prefer.

Thanks a lot for all your attention.

**Comment by onovotny** [comment]
I've just pushed a test implementation of this to the Zeroconf MyGet feed. Can you give it a shot and let me know?

The MyGet feed is here: https://www.myget.org/F/zeroconf/api/v2

Use the `2.4.1-observable0001` version. I've added an impl to the Resolve and Browse that returns an IObservable. That can be used along with a long scan time to keep a stream of updates coming. 

I have yet to test it but it's a pretty simple wrapper so I don't expect too many issues.

**Comment by Sparksteam** [comment]
Great Oren, I'll give a spin tomorrow. Will the scan completion notification still come back the same way, i.e. nulls?






Sent from Windows Mail





From: Oren Novotny
Sent: ‎Thursday‎, ‎November‎ ‎12‎, ‎2015 ‎6‎:‎58‎ ‎PM
To: 'onovotny/Zeroconf'
Cc: Allan Chin





I've just pushed a test implementation of this to the Zeroconf MyGet feed. Can you give it a shot and let me know?

The MyGet feed is here: https://www.myget.org/F/zeroconf/api/v2

Use the 2.4.1-observable0001 version. I've added an impl to the Resolve and Browse that returns an IObservable. That can be used along with a long scan time to keep a stream of updates coming. 

I have yet to test it but it's a pretty simple wrapper so I don't expect too many issues.

**Comment by onovotny** [comment]
There shouldn't be any nulls, instead, IObservers get OnNext, OnError and OnComplete calls. 

You could implement IObserver directly or use the Rx implementations. Rx is really powerful, think Linq for streaming data.

**Comment by Sparksteam** [comment]
Excuse my ignorance Oren, but what can I do with your MyGet feed? Can I download the package source from there so I can take a look at what you’ve done?

 

Thanks,

 

Allan

**Comment by onovotny** [comment]
You should be able to add a nuget.config file alongside your sln file that has custom feeds in it. Then it'll show up in the IDE; you may need to restart VS for it to get picked up.

Here's an example from Humanizer:
https://github.com/Humanizr/Humanizer/blob/features/integration/integration/nuget.config

**Comment by Sparksteam** [comment]
Ok, I’ve added the package source for your myget feed, but when I install Zeroconf from that source, the only versions I see are 2.4.1 and Latest Stable 2.4.1 which appear to still have the original method signatures. 

 

My NuGet.Config file has this.

 

  <packageSources>

    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />

    <add key="HP Packages" value="http://san-nexus-wip.cscr.hp.com:8080/nexus/service/local/nuget/cscr_wip/" />

    <add key="Zeroconf v2" value="https://www.myget.org/F/zeroconf/api/v2" />

  </packageSources>

 

How do I specify 2.4.1-observable0001 version?

 

Thanks

**Comment by onovotny** [comment]
Did you check the "prerelease" box in NuGet?

**Comment by Sparksteam** [comment]
Ahhh…. as you can tell, I’m a nuget newbie.

 

Anyway, the IObservable implementation works well. A couple of things though….

 

1.       Can you add support for an Enumerable list of protocols?

2.       Can you add support for cancelling the scan via a CancellationToken?

3.       Would it be too much trouble for you to implement a scanning status. I could implement it myself in the client based on observed events, but it seems like a reasonable thing for the PCL to provide. What do you think?

 

Thanks for accommodating.

 

Allan

**Comment by onovotny** [comment]
So Rx does work a little different. Each time you call Subscribe on the IObservable, you start a new scan. Calling Dispose will cancel early, so that's how you do it in that model (and also why cancelation tokens aren't in the signature.

Take a look at http://introtorx.com/, it has a lot of good tutorials on how Rx works. For finite sequences, like this one, you can also call ToEnumberable() to get a list of them but that largely defeats the point for most Rx usage patterns.

**Comment by Sparksteam** [comment]
Thanks Oren – even the Intro to Rx is like rocket science. But then some of the more advanced features of Linq itself is still rocket science to me.

 

So the scan happens on the call to Subscribe() and not on Resolve(). What happens if a subsequent call to Subscribe() happens before the initial scan has completed? Does a second scan start on a separate thread while the initial scan just continues?

**Comment by onovotny** [comment]
The way it works now is that each scan will take a lock as the network interface is a shared resource. We can't have two scan's going in parallel.
You can see this here:
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.Shared/ZeroconfResolver.cs#L168

So if you call subscribe multiple times, the later ones will wait to start until the earlier one finishes.

That said, Rx has a way of doing this -- it's the Switch() construct. It takes a sequence of sequences and always takes the most recent one -- and disposes the old ones. 

So you could do something like 

protocols.Select(p => ZR.Resolve(p, ... )).Switch().

That's sorta silly in this case as you'd only ever take the last protocol but that's the idea. 

I can add an overload that takes an Enumerable set of protocols, that's easy. I just wanted to get the idea out for you to test.

**Comment by Sparksteam** [comment]
No Oren, I do not intend to support parallel scans. I was just curious. With the protocol list, I think we'll be set. Thanks again.






Sent from Windows Mail





From: Oren Novotny
Sent: ‎Friday‎, ‎November‎ ‎13‎, ‎2015 ‎12‎:‎30‎ ‎PM
To: 'onovotny/Zeroconf'
Cc: Allan Chin





The way it works now is that each scan will take a lock as the network interface is a shared resource. We can't have two scan's going in parallel.
You can see this here:
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.Shared/ZeroconfResolver.cs#L168

So if you call subscribe multiple times, the later ones will wait to start until the earlier one finishes.

That said, Rx has a way of doing this -- it's the Switch() construct. It takes a sequence of sequences and always takes the most recent one -- and disposes the old ones. 

So you could do something like 

protocols.Select(p => ZR.Resolve(p, ... )).Switch().

That's sorta silly in this case as you'd only ever take the last protocol but that's the idea. 

I can add an overload that takes an Enumerable set of protocols, that's easy. I just wanted to get the idea out for you to test.

**Comment by onovotny** [comment]
This is now in the 2.5.0 package on NuGet. Thanks!

**Comment by Sparksteam** [comment]
Thank YOU, Oren.






Sent from Windows Mail





From: Oren Novotny
Sent: ‎Monday‎, ‎November‎ ‎16‎, ‎2015 ‎6‎:‎08‎ ‎AM
To: 'onovotny/Zeroconf'
Cc: Allan Chin





This is now in the 2.5.0 package on NuGet. Thanks!

**Comment by Sparksteam** [comment]
Sorry Oren, I have another question…

 

For OnError(), are there errors to which scanning will stop? Or does it top on any error?

 

Thanks.

**Comment by Sparksteam** [comment]
Hey Oren – it looks like I’m running into that Profile7 issue again with 2.5.0. 

 


Severity

Code

Description

Project

File

Line


Error

 

Couldn't find the required information in the lock file. Make sure you have .NETPortable,Version=v4.5,Profile=Profile7 mentioned in your targets.

Bonjour.Xamarin

 

 

 

I’ve attached my project.json and project.lock.json for your perusal.

 

Thanks,

 

Allan

**Comment by onovotny** [comment]
Hi,

The NuSpec appears correct; nothing changed there. Attachments don't work on email replies to GitHub issues.

**Comment by Sparksteam** [comment]
Regarding that



 Profile7 issue...

**Comment by Sparksteam** [comment]
[project.json.txt](https://github.com/onovotny/Zeroconf/files/36022/project.json.txt)
[project.lock.json.txt](https://github.com/onovotny/Zeroconf/files/36021/project.lock.json.txt)

**Comment by onovotny** [comment]
Not really sure what the issue is there... with those, it's a UWP project and is using the portable-win81+wpa81 version. I just tried on a blank UWP project and had no trouble adding it.

**Comment by Sparksteam** [comment]
Yeah, I build a test app with a test PCL. I was able to reference the latest Zeroconf and also had no trouble. I’m looking deeply into our production software solution to see what the difference is.

 

What a pain!

 

I’ll let you know what I find.

 

Thanks Oren.

**Comment by Sparksteam** [comment]
Oren - are you aware of this new MSFT initiative?

https://docs.nuget.org/Consume/ProjectJson-Intro

**Comment by onovotny** [comment]
Yes, I am very familiar with that

**Comment by Sparksteam** [comment]
Ok Oren, not sure what exactly was happening, but I re-installed your preview package via the Package Manager rather than via the projects.json file, got everything working, then did an Update from the Package Manager to 2.5.0. Everything’s good now. I’m guessing my project and environment got messed up somewhere.
