### ISSUE TITLE
Errror with demo code

### ISSUE THREAD

**Issue by vbisbest** [onovotny/Zeroconf#27]
Getting an error with both of your examples.  Running on Windows VS2013.

Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.

Thanks.

**Comment by onovotny** [comment]
What kind of project, was this a first chance or unhandled exception?

**Comment by onovotny** [comment]
Closing out for lack of additional info. Please reopen if this still happens and can be reproduced.
