### ISSUE TITLE
Reactive enforces en-US locale

### ISSUE THREAD

**Issue by queequac** [onovotny/Zeroconf#29]
So far I have been using Zeroconf up to version 2.4.0.
But recently I gave the latest version 2.5.0 a try, realizing that its usage of Reactive enforces the en-US locale. (See first two lines from command line below.)

```1>MakePRI : warning 0xdef00522: Resources found for language(s) 'en-us' but no resources found for default language(s): 'de-DE'. Change the default language or qualify resources with the default language. http://go.microsoft.com/fwlink/?LinkId=231899```
```1>MakePRI : warning 0xdef01051: No default or neutral resource given for 'System.Reactive.Strings_Linq/CANT_ADVANCE_WHILE_RUNNING'. The application may throw an exception for certain user configurations when retrieving the resources.```
...

For Windows 10 apps this leads even to an additional "supported language" entry for English, even if the app does NOT. This demands to create an additional package description in English for the store. :/

For the moment I will keep my hands off version 2.5.0, as long as it cannot be used in a really language neutrale manner.

**Comment by onovotny** [comment]
Looking into this with the Store team...this seems odd.

**Comment by onovotny** [comment]
Okay, there is a bug in VS 2015 that they've identified...will be fixed eventually.

There's a workaround now though: Add
`<SkipIntermediatePriGenerationForResourceFiles>false</SkipIntermediatePriGenerationForResourceFiles>`

Into the first `<PropertyGroup>` section of your project file for your app. That should fix it.

**Comment by queequac** [comment]
I have updated to VS2015 Update 1 over the weekend... and trying to check this workaround, the problem seems not to arise in this setup anymore. Maybe it got fixed along with this vs-update?

**Comment by onovotny** [comment]
Closing for now then. There was/is a bug but fortunately there's a workaround too. Thanks

**Comment by queequac** [comment]
Just some side note, the bug was actually still there. Thanks for the workaround! Hopefully there will be also an official vs bug fix some day...
