### ISSUE TITLE
Core CLR

### ISSUE THREAD

**Issue by risogolo** [onovotny/Zeroconf#30]
Hi, Is it possible to add support for Core CLR platform, I'd like to use the library within UWP application and ASP.NET 5 WebAPI project (Core CLR)

**Comment by onovotny** [comment]
This will work today with ASP.NET 5 on the desktop CLR and UWP as it uses the Win81 version. It won't work for ASP.Net 5 on Core CLR. I agree this would be a nice addition.

**Comment by onovotny** [comment]
One current issue is that Rx doesn't support CoreCLR yet. I can release a version without the IObservable interfaces though.

https://github.com/Reactive-Extensions/Rx.NET/issues/148

**Comment by onovotny** [comment]
As an update, this is pretty much done/ready, just need the .net core packges to GA

**Comment by onovotny** [comment]
This is complete in the `netstandard` branch but is blocked pending resolution of https://github.com/dotnet/corefx/issues/9817

**Comment by jakeswenson** [comment]
Any update on this issue? i'd really like to use this library with my new dotnet core console app.

**Comment by onovotny** [comment]
I should be able to get this live shortly

**Comment by jakeswenson** [comment]
Thanks for the quick update! I'll keep an eye out for it to show up on nuget.
Thanks again!

**Comment by jakeswenson** [comment]
Anything that i can do to help or test for you? Not sure whats remaining as it seems like the code is there but needs to be merged... i'll try cloning and building but i'm on a mac so we'll see how that goes!

**Comment by onovotny** [comment]
This should be fixed in 2.8.0, now on NuGet. Please re-open if this is still an issue.
