### ISSUE TITLE
Query SRV records

### ISSUE THREAD

**Issue by vbisbest** [onovotny/Zeroconf#31]
Does your library support querying DNS for SRV (Service) records?  I am looking to somehow get access to DNSServiceQueryRecord on iOS.  Thanks!

**Comment by onovotny** [comment]
Hi @vbisbest,

Zeroconf is not a DNS querying library. While it is true that mDNS does use DNS records, it doesn't make queries in the same way. There might be some of the underlying parsing that could be helpful to you though.
