### ISSUE TITLE
UTF-8 in the DisplayName isn't processed correctly

### ISSUE THREAD

**Issue by Lakritzator** [onovotny/Zeroconf#34]
This is a nice project, and seems to work quite well.

Here a little bug I noticed:
I have an Airplay device, Apple TV 3, which is called "Apple TV (Büro)".
When I discover the service, the DisplayName is "AppleÂ TV (BÃ¼ro) (2)"
I don't know what is behind "Apple", but it's definitively clear that the "ü" (u-umlaut) is not processed correctly.

As far as I could find in the documentation, this should not cause any problem.
Just in case I tried the first Windows App Store app I could find to test this, this was "AirPlayTo Audio", and there it was displayed correctly.

I guess, didn't look in the code yet, everything is processed as ascii while UTF-8 should be used.

P.S.
Although I really like reactive extensions, I wonder how much of it you are really using.
Your dll is ~39KB, the reactive dll's are 828KB (of which the System.Reactive.Linq.dll is 692KB!!)
Surely in real life one MB more or less is not so dramatic, if I compare the size of the Greenshot installer (about 1.5MB) to the size this will grow when I add Zeroconf functions: it will almost be 2x the size. Just something to think about, as soon as there are good reasons for it I'm not complaining.

Thanks for the neat project!

**Comment by Lakritzator** [comment]
I think the problem is in the RecordReader "ReadDomainName".
It should just collect the bytes which form the name in an array, and use "Encoding.UTF8.GetString(bytes);" when everything is there.

Will see if I can supply a pull-request for this.
But it might actually make more sense to use the nuget package from: https://github.com/ghuntley/Heijden.Dns
And I should supply the pull request there?
I believe that domain names are actually supporting UTF-8 (at least limited)...
Will need to check though.

**Comment by Lakritzator** [comment]
I also opened an issue here: https://github.com/ghuntley/Heijden.Dns/issues/2
Just in case...

**Comment by onovotny** [comment]
Thanks -- a PR would be welcome; please apply the PR to here. The DNS code was based on that other project as you saw, but this has its own version for maintainability.
