### ISSUE TITLE
Exception when doing ResolveAsync() on iOS connected to WIFI direct Access Point device

### ISSUE THREAD

**Issue by jeremycookhp** [onovotny/Zeroconf#36]
Hi,

As you are aware, iOS doesn't support true WIFI direct Peer 2 Peer.   But WIFI direct devices can still support an ad-hoc access point mode by which iOS can connect.   We are using the latest ZeroConf package on Xamarin.iOS to attempt to do Bonjour discovery over such a connection, and we are getting a exception of the following type thrown:

InvalidOperationException: Bind has already been called for this socket

ResolveAsync() does succeed in this same scenario using Xamarin.Android.    

Any thoughts on this?   I've attached the full exception callstack that we see.

Thanks
Jeremy
[crash stack.txt](https://github.com/onovotny/Zeroconf/files/145403/crash.stack.txt)

**Comment by jeremycookhp** [comment]
We were referencing Version 2.5.0 using Nuget.   I pulled down the master code today, build locally, and the issue has been resolved.   Not sure when the next Nuget release will be, but hopefully that will include the fix.  Thanks!

**Comment by onovotny** [comment]
Great to hear, will try to get an updated release out shortly.

**Comment by onovotny** [comment]
Sorry for the delay...I can see there's been a few changes that could affect this since 2.5.0. I'll get an update out very soon.

**Comment by jeremycookhp** [comment]
Hi Oren, awesome, thanks!   I wanted to bring something else to your attention, this might be worthy of it's own thread, but here it is.  I've pulled down the trunk code and have been building locally.   What I notice on iOS only is that every so often the call to UdpClient.SendAsync() will take minutes to return.  This only seems to happen on certain WIFI connections.   here's the code:
`
                        Debug.WriteLine($"About to send on iface {adapter.Name}");
                        await client.SendAsync(requestBytes, requestBytes.Length, broadcastEp)
                                    .ConfigureAwait(false);
                        Debug.WriteLine($"Sent mDNS query on iface {adapter.Name}");
`
Anyway, when it's in this state, the task cannot be cancelled.   I know this is Mono implementation and perhaps it's just a bug in that.   
Thanks
Jeremy

**Comment by onovotny** [comment]
Can you please try Zeroconf.2.5.1-bld012 from this MyGet feed: https://www.myget.org/F/zeroconf. Please confirm that works for all of your scenarios and I can push that out to NuGet as 2.5.1.

Thanks!

**Comment by jeremycookhp** [comment]
Hi Oren,
I am having trouble with building iOS right now, so I can't verify the original defect reported.   However, the new release still has an issue on UWP.   UWP is only searching on the GetInternetConnectionProfile network adapter and not all adapters.  I think it might be related to the #if !WINDOWS_PHONE logic in there.   It's not falling into the #else case where it searches all adapters.

Once I get my certificate issue sorted out on iOS, I'll test that case as well.
Thanks
Jeremy

**Comment by onovotny** [comment]
@jeremycookhp Good catch. I never updated the WinRT code when I made the Net45 code support a better way of using all interfaces.

I've opened up a separate issue to track this #43. I don't want to hold up getting 2.6 out though if the rest works as it's new behavior.

**Comment by jeremycookhp** [comment]
Hi Oren,
Ok I was able to run on iOS today and confirmed that Zeroconf.2.5.1-bld012 works properly.

Thanks!

**Comment by onovotny** [comment]
Fantastic. I'll release what's currently in master now as 2.6 and we can see about fixing up the UWP/WinRT support for #43.

**Comment by onovotny** [comment]
2.6.0 is now on NuGet.org.
