### ISSUE TITLE
Service Publishing

### ISSUE THREAD

**Issue by donpark** [onovotny/Zeroconf#4]
This package only supports enumeration of services published via mDNS.

If no service publishing is supported, stating this in README would save developers
looking to publish services some time.

Thanks.

**Comment by mgamache** [comment]
I agree.

**Comment by BoteRock** [comment]
this should be stated in the readme.
this package is only for zeroconf discovery, not for zeroconf publishing

**Comment by onovotny** [comment]
Done. Though a PR to add service publishing would be accepted.
