### ISSUE TITLE
WinRT/UWP should scan all interfaces

### ISSUE THREAD

**Issue by onovotny** [onovotny/Zeroconf#43]
Right now WinRT/UWP code only looks at the internet-connected profile.
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.RT/NetworkInterface.cs#L93

This code needs to be updated to try all interfaces that support multicast like the Net45 version does.

**Comment by queequac** [comment]
When writing the UWP library (compare #44), I immediately tried to add support for multiple interfaces just like the net45 version does. But unfortunately RT and UWP seem not to provide sufficient information that would allow to do the trick of the filtering of unfavourable interfaces out of the box.

For the moment the new UWP library sticks also to the internet-connected profile. But because I am 
interested in a proper mdns support for my UWP project, I will also give some thought to solving this issue.

**Comment by jeremycookhp** [comment]
Hi Oren, I just tested your version 2.7.0 private build, and it looks to have fixed this issue?   Are you close to releasing a new version?  Looks like you've been unifying the network adapter stuff...  
Thanks!
Jeremy

**Comment by queequac** [comment]
@jeremycookhp The modification is in line 94 of the NetworkInterface.cs used by RT and UWP:
`await socket.BindServiceNameAsync("5353") // binds to the local IP addresses of all network interfaces on the local computer if no adapter is specified`

In the previous version the adapter associated with the Internet Profile was passed... actually, I think letting Windows decide which adapters are capable of multicasting is the best approach.

I am also waiting for the new nugget package to be released. Don't want to put a private build into my projects.

Best regards, Roland

**Comment by onovotny** [comment]
Does the current 2.7.0 version address this issue or is there more work to be done here?

Thanks!

**Comment by jeremycookhp** [comment]
Hi Oren,

Yes, we’ve been using 2.7.0 and it’s working well for UWP, iOS, and Android.

Thanks!
Jeremy

**Comment by onovotny** [comment]
@jeremycookhp @queequac Just curious -- are the apps that you're using Zeroconf in public / I the stores? I could add a section on the main GitHub page that lists apps using this if you'd be interested.

**Comment by jeremycookhp** [comment]
Not yet, we have a ways to go.  Hopefully by next year.   The app will facilitate scanning and workflow destinations for HP devices that have a scanner.   But at that time, sure we’d be happy to have you mention us!!

Jeremy

**Comment by queequac** [comment]
Hi Oren,
I am using Zeroconf to detect Chromecast devices (with fallback to UPnP discovery) for over an year now in this app: [Meine Mediatheken](https://www.microsoft.com/en-us/store/apps/meine-mediatheken/9nblggh0j2rt)
It targets German-speaking markets only, so there is no English version of that app, sorry. :)
