### ISSUE TITLE
Resolve() on WIFI networks has varying results.

### ISSUE THREAD

**Issue by jeremycookhp** [onovotny/Zeroconf#47]
We are using Zeroconf to do service discovery of printer / scanner type devices.   I find that on LAN networks, the results returned by Resolve() are very consistent, and usually return within a few seconds of issuing the Resolve().   However, on WIFI networks, especially on Android/iOS, I am finding quite a bit of variance in what is found.   Sometimes I get a few devices, sometimes none, sometime lots.   And, it doesn't seem to matter what i set the discoveryTime value at.   If it doesn't find them in the first few seconds, longer discoveryTimes have no relevance.  As such, I find that I've had to implement a "continuous discovery" mechanism by which I just submit Resolve() requests every few seconds, and then aggregate the results and throw out duplicates.   I don't think this is how it should work, but perhaps this is what was intended?

Thanks
Jeremy

**Comment by jamespettigrew** [comment]
I've been experiencing the same issue. If I use Wireshark to observe the network after calling Resolve() I can see an mDNS response packet go out but the mobile devices seem to miss it quite frequently--I've put it down to poor multicast implementations. A possibly hacky solution would be for Zeroconf to send out a handful of lookups with each call to Resolve(), with the probability of missing all the response packets being very low.

**Comment by onovotny** [comment]
I'm not really sure what the best fix is here if the issue is in the mobile devices themselves. As you mentioned @jeremycookhp, you could always call it multiple times and aggregate the results. If you use the `IObservable` version, Rx makes it really easy to combine many different invocations and return distinct results.

Probably using .Switch().Distinct()...

**Comment by jeremycookhp** [comment]
Hey Oren,

We consistently observe that regardless of the scan time specified, nothing really gets reported after about 3 seconds.   It would seem that a useful optimization to Zeroconf would be to have it internally run smaller duration Resolve() calls over the specified scan period.    Just a thought…

Jeremy

**Comment by onovotny** [comment]
Theoretically, most Zeroconf devices should be responding quicker than that -- it's not super clear to me that you need a long response time anyway. Are you finding that you get different results when you are constantly rescanning?

**Comment by jeremycookhp** [comment]
Yes, we get different results almost every time over a WIFI network.  Sometimes, no results at all.    Over LAN, it seems to be much more consistent.

Jeremy

**Comment by onovotny** [comment]
Maybe what's needed is a helper class that does this external to the core logic. The core logic does what it does, so there doesn't seem to be a good reason to commingle things.

I could imagine an `IObservable<IZeroconfHost> UnreliableNetworkHelper.AggresivelyScanForThings()` method that uses the existing methods but calls that repeatedly and dedups the results.

**Comment by jeremycookhp** [comment]
Yes, that seems like a logical place to do this.   I am guessing that other folks would take advantage of this as well, and it would alleviate clients having to do their own mechanisms to continuously refresh and aggregate the results.

Jeremy

**Comment by onovotny** [comment]
Here's what I'm thinking --

It'll return an `IObservable<IZeroconfHost>` when you call `Foobar.CreateScanner()`...

Then, when you call the `Subscribe()` method on the `IObservable`, it'll begin the scan. It'll only return distinct `IZeroconfHost` instances. When the subscription is Disposed, scanning will stop.

Open questions: How much configuration should that `Create(..)` method take? Does it need both Resolve and Browse or just one of them? Should it effectively mirror all of the parameters except the scan time or can it be simplified?

Thoughts?

**Comment by jeremycookhp** [comment]
Looks sound to me.   We are only using Resolve() since we know the service types in advance we want to scan for.   So I’d start with just that.   As far as other configuration, the only thing that it might need would be the retry loop time.  My investigation shows that everything is usually discovered in the first 3-4 seconds and nothing after that.  But you might consider offering that as an optional parameter that defaults to 4 seconds.   The other parameters can be mirrored.  FWIW, we only specify the service types, and the discovery time, and leave all the rest at defaults.

Thanks
Jeremy

**Comment by onovotny** [comment]
It's building now, but look for 2.7.1 on the MyGet CI feed shortly. There's *Continuous methods on the `ZeroconfResolver` that will do this now.

I'm a bit hesitant to put it in permanently though because it's really just two Rx operators. That said, it may be common enough to leave this one scenario as baked in.

**Comment by jeremycookhp** [comment]
Thanks Oren, will test this out next week!

Jeremy

**Comment by jeremycookhp** [comment]
Hi Oren,

I tested today and this new mechanism seems to be working well.   We would use this if you chose to include it.

Thanks for your time on this.

Jeremy

**Comment by onovotny** [comment]
That code is in the released bits on NuGet. I'll keep it around, but it just goes to show how Rx makes things easy :)
