### ISSUE TITLE
Not detecting linux IoT device with Apple's mdnsd

### ISSUE THREAD

**Issue by choikwa** [onovotny/Zeroconf#49]
I am seeing the multicast packet from BrowseDomainsAsync() on the device, but nothing sent out. Is this is tested to work with mDNSResponder from Apple?

**Comment by onovotny** [comment]
Hi @choikwa Not sure I fully understand your question? What kind of application are you trying this with, do you have the right local network permissions set?

This should detect any device that responds to mDNS/Bonjour multicast requests.

**Comment by choikwa** [comment]
I also tested on linux laptop, but problem seems to be blocked port somewhere.
