### ISSUE TITLE
Add version to assemblies

### ISSUE THREAD

**Issue by queequac** [onovotny/Zeroconf#50]
Currently the assemblies do all lack a proper version information.
It would be really great if the zeroconf assemblies could be versioned (in sync with the nuget packages).

Personally I do have references to open source components, their version, license and stuff in the "about" section. And it would be much easier if I could simply use the assembly version their instead of adjusting the version each time manually. :)

Since RT and Portable do already have a shared assembly info, I added the (upcoming 2.7) version there and added a link to this file for the UWP project also.
PR follows, would be great, Oren, if you could keep that version incremented along with your public nuget releases.

By the way, any chance for the 2.7 nuget package soon? I am waiting for weeks to get the UWP assembly through nuget, since the RT variant is useless under Windows 10. Would really appreciate if you could kick it to nuget.

Thanks, Roland

**Comment by onovotny** [comment]
Hi,

2.7.0 is on NuGet currently and has the Win10 version. Looking at the binaries there, the assembly info's are already correct as `GitVersion` updates the assemblyinfo's on the CI build. It contains the File Version, Assembly Version and Assembly Informational version for each project type.

Are those not showing up for you?

**Comment by queequac** [comment]
My fault, Oren.
First of all I looked for the new nuget package nearly on daily basis, but not when sending the PR.
And you are right, the latest packages do have the version of the nuget package. Unfortunately I just checked my private builds and the 2.3.3 package which did indeed have 1.0.0.0 as version and not the nuget version. 

As I said, my fault. Closed the PR and this Issue. :)
