### ISSUE TITLE
Hosting on specific Network Adapter

### ISSUE THREAD

**Issue by dperkinsjr** [onovotny/Zeroconf#53]
Having an issue where Bonjour chooses to host the service on whatever Network Adapter it wants to. In cases where we're running VMs the service will all of a sudden end up on that Network Adapter when we want it on a different one. Wondering if there's a way to specify which one we'd like to host it from, or if this could be a feature implementation.

**Comment by dperkinsjr** [comment]
Kinda a work around for our solution. Instead of attempting to force Bonjour to host on a certain network adapter, or on a certain IP. Our solution knows which IP we actually want to use, simply add that as a Text Record in the Property Set. Pull that IP from the Property Set and connect to that instead of the IP of the service itself.

Only other solutions we saw were out of the scope of this git.

**Comment by onovotny** [comment]
Hi,

Not sure where the Zeroconf issue is here? Zeroconf cannot publish services for discovery. It can scan the network to locate them however.

**Comment by dperkinsjr** [comment]
Zeroconf doesn't register itself, but I believe it accesses whatever running instance of Bonjour and calls the register command. An example of what we're doing [here on stackoverflow](http://stackoverflow.com/questions/599846/how-to-register-a-service-with-mono-zeroconf).

**Comment by onovotny** [comment]
This is Zeroconf, not `Mono.Zeroconf`. Very different project.

**Comment by dperkinsjr** [comment]
Oh very sorry then. Maybe I'll bring up the issue on that project.

**Comment by onovotny** [comment]
No worries. If you need to scan for Zeroconf services on your network, this library supports virtually all .NET platforms -- which is its main purpose.
