### ISSUE TITLE
Confused about the API

### ISSUE THREAD

**Issue by tealshift** [onovotny/Zeroconf#58]
Hi, I'm looking to create my own Bonjour service advertisement, and this looks like the general tool to do that (though I'm new to network dev and I might be lost). I see the docs on the front page showing how to enumerate the available Bonjour services (and it worked) but I guess I'm looking for a more extensive documentation that includes advertisement.
I tried Mono.Zeroconf before but ran into problems, and this project looks like a good alternative since you're actively supporting it. :)

**Comment by onovotny** [comment]
Hi @tealshift, the library only supports querying for devices not publishing them. I'd welcome a PR that adds that support.

**Comment by tealshift** [comment]
Thanks for clarifying. Hopefully I can find some way to do this on Windows.
