### ISSUE TITLE
Resolver returning incorrect devices

### ISSUE THREAD

**Issue by dannormington** [onovotny/Zeroconf#59]
When calling the ZeroconfResolver.ResolveAsync method and specifying "_googlecast._tcp.local." as the protocol I will intermittently see results that are not Chromecast devices. Sometimes AppleTV or other Apple devices will show up in the results.

**Comment by queequac** [comment]
Cannot confirm this being a general issue. I am sending exactly the same request within my project and I always get Chromecasts only. (Even though I have to admit that I personally do not have any Apple devices and my released app would discard results that do not fit anyhow.)

**Comment by dannormington** [comment]
@queequac What are you adding to your released app that will discard results that do not fit? Are you checking that the Services returned with the device match the protocol?

**Comment by onovotny** [comment]
Could Apple devices be responding to the _googlecast query as a compatibility measure?

**Comment by dannormington** [comment]
I'm going to add some debug statements to display the services key after the resolve is complete. The problem for me is that it happens very rarely.

**Comment by dannormington** [comment]
It appears that this may be an easy fix within my application. All devices that I don't want to present to the user do not contain the _googlecast._tcp.local. service key. Some of the devices returned don't contain any services at all.

**Comment by writzx** [comment]
This is exactly what is happening in one of my projects. Although I used ZeroconfResolver.ResolveAsync("_telnet._tcp.local.") method but it also returns other "_http._tcp.local." or some others (e.g. _csco-sb._tcp.local.) as well. I couldn't understand this abnormality however it is happening every time I use the method in my code. I am pretty new to this topic so pardon any mistakes.

**Comment by onovotny** [comment]
I wonder if we're picking up responses sent to other devices on the network making similar inquiries. It is mulitcast after all.

I think a fix for this could simply be for ResolveAsync method to filter out responses that don't match the request.

**Comment by writzx** [comment]
That's exactly what I am doing right now after receiving the responses using ResolveAsync.

**Comment by onovotny** [comment]
This should be fixed in 2.8.0. Please re-open if this is still an issue.
