### ISSUE TITLE
Mono.Zeroconf  library is not supported for Windows phone8

### ISSUE THREAD

**Issue by vedd** [onovotny/Zeroconf#6]
I want to register a service using Mono.Zeroconf in windows phone 8 but when i try to add this library in wp8 using Nuget then it shows me error that 

Install failed. Rolling back...
Install-Package : Could not install package 'Mono.Zeroconf 0.9.0.0'. You are trying to install this package into a project that targets 'WindowsPhone,Version=v8.0', but the 
package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Mono.Zeroconf
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by onovotny** [comment]
The Mono.Zeroconf library is a totally different library than this one.
