### ISSUE TITLE
DisplayName on Chromecast is incorrect

### ISSUE THREAD

**Issue by dannormington** [onovotny/Zeroconf#63]
This had been previously working but I noticed today that The DisplayName for Chromecast based devices appear to be a combination of the "md" and "id" properties. For instance, the result of the ResolveAsync method is returning a Chromecast device with a name following the pattern below:

**_md-id_**

While investigating the service properties in the debugger it appears that the "fn" property should be used for the DisplayName.

**Comment by queequac** [comment]
Well, this is no Zeroconf issue, but Google changed the behaviour with the last firmware update.
This ensures unique service names while the friendly name reflects the name the user gave its device.

I'd suggest to subscribe for the preview Firmware, then you'd have realized this some weeks ago. :)

**Comment by dannormington** [comment]
I understand that Google changed the firmware but it seems that a property named "DisplayName" should be using the "friendly name" and not the device id. For uniqueness I would use the "id" of the device and not the "DisplayName" within my application. I can easily change our code to use the "friendly name" instead. Please let me know if this is something that you plan on changing.

**Comment by onovotny** [comment]
Zeroconf is meant to be as neutral as possible to the returned DNS records and metadata. It does not interpret specific hosts as that would be impossible to keep up with. It's really up to the application to interpret the results from the devices it expects to discover.

**Comment by dannormington** [comment]
Totally understand. Thanks for researching this issue.
