### ISSUE TITLE
The async ResolverLock seems to serve no purpose but slow down the query

### ISSUE THREAD

**Issue by zone117x** [onovotny/Zeroconf#64]
We've removed the async lock in our fork here: https://github.com/PingmanTools/Zeroconf/commit/3cd173c98f492880549e9b6ccd29f96df6576ece?w=1

It was slowing down lots of queries at once and it doesn't seem to be needed. I'd do a pull request but want to get some input first (also the whitespace got all messed up).

**Comment by onovotny** [comment]
@zone117x the lock was put in there as only one scanning operation can be done at a time. Otherwise, the multicast results of different queries may not align.

Have you tested the code running multiple queries on different threads, at the same time, and proven the results don't conflict (and that you don't get exceptions from trying to bind to the same local port with different threads at the same time?)

**Comment by onovotny** [comment]
Closing as I believe the lock is required to prevent overlap in query/responses.

**Comment by zone117x** [comment]
Sorry for the late response. I believe you are correct about the overlap in responses. However, we are using this lib to discover all available Zeroconf devices with code like this:

```
var bufferBlock = new BufferBlock<IZeroconfHost>();

var browseDomainsTask = ZeroconfResolver.BrowseDomainsAsync(retries: 1, scanTime: TimeSpan.FromMilliseconds(500), cancellationToken: cancelToken);
ObserveTaskException(browseDomainsTask);

var finishedTask = await Task.WhenAny(browseDomainsTask, cancelTask.Task);
if (finishedTask == cancelTask.Task)
{
   return;
}

var domains = (await browseDomainsTask).Select(d => d.Key).ToList();

var resolveTask = ZeroconfResolver.ResolveAsync(domains, scanTime: TimeSpan.FromSeconds(2), retries: 1, cancellationToken: cancelToken, callback: dev =>
{
   bufferBlock.Post(dev);
});
ObserveTaskException(resolveTask);

var bufferCompleterTask = resolveTask.ContinueWith(t => bufferBlock.Complete());
```

We need to populate the GUI with found devices as soon as possible, and we don't care about the query overlaps since we filter at duplicates when they come in. This is why I removed the resolverlock in our fork.

Perhaps the ZeroconfResolver.ResolveAsync method could be passed an optional parameter specifying whether the lock should be used. Or maybe add a new method only for the purpose of discovering all devices. 

Would be great to get that upstreamed so we don't have to maintain a fork. What do you think?
