### ISSUE TITLE
The Reactive/Observable feature should be an addon nuget package

### ISSUE THREAD

**Issue by zone117x** [onovotny/Zeroconf#65]
We don't need the feature and avoid including unused dependencies in our product, so we removed the System.Reactive package dependency and ZeroconfResolver.Observable.cs file.

https://github.com/PingmanTools/Zeroconf/commit/1280a0da1ae0f318e451c998de84a517e6b2e5b7

It seems like most users of the Zeroconf lib probably don't use the feature. I think it should be pulled out into its own project and published as an addon nuget package.

**Comment by onovotny** [comment]
@zone117x at this point, that would be a breaking change. Also, Rx is helpful library for things that deal with push based sequences, which scanning for devices certainly is.

There are no plans to remove use of Rx; in the end, it adds very little size and on platforms which support AOT/.NET Native, adds almost nothing.
