### ISSUE TITLE
CreateMulticastLock requires ChangeWifiMulticastState permission

### ISSUE THREAD

**Issue by softlion** [onovotny/Zeroconf#68]
The quickstart doc should be updated to include this requirement.

    [assembly: UsesPermission(Android.Manifest.Permission.ChangeWifiMulticastState)]

**Comment by onovotny** [comment]
Done in https://github.com/onovotny/Zeroconf/commit/46d813a9b6823af4a0de9536098467a09849ebd7, thanks!
