### ISSUE TITLE
Also query SRV records

### ISSUE THREAD

**Issue by softlion** [onovotny/Zeroconf#69]
Should'nt you also query SRV records in addition to PTR records ?

**Comment by onovotny** [comment]
According to the RFC, queries should be for PTR records and the responses contain SRV and TXT records:
https://tools.ietf.org/html/rfc6763#page-3

Unless I'm missing something?

**Comment by onovotny** [comment]
As per #70, there's now an option to query for ANY records. For a non-conforming server, that should work.... can you try that and reopen this issue if there's still an issue?
