### ISSUE TITLE
Mdns query is of type PTR instead of ANY.

### ISSUE THREAD

**Issue by bberrevoets** [onovotny/Zeroconf#70]
Hello,

The query send by the example, is creating a mDns query with the type of PTR instead of ANY. (see attachment.) That is why not al services are responding. Is there a way to correct this?

Greetings Bert.
![capture](https://cloud.githubusercontent.com/assets/4933105/21580829/7954ca00-d013-11e6-9c9c-f73063a1d699.PNG)

**Comment by onovotny** [comment]
I thought there was a reason for this but I'll need to investigate. It's an easy change either way.

**Comment by onovotny** [comment]
It was changed in this commit:
https://github.com/onovotny/Zeroconf/commit/e6fe884812d8e55a8f45dfb36bbac486881a56ec

I can't seem to find the related issue number though. Need to check the spec to see what's "correct" here.

**Comment by onovotny** [comment]
According to the RFC, queries should be for PTR records and the responses contain SRV and TXT records:
https://tools.ietf.org/html/rfc6763#page-3

Unless I'm missing something?

**Comment by bberrevoets** [comment]
I am trying to query a Parrot Bebop drone, when I change it to ANY, the drone is responding, with the query set to PTR, I get no results from the drone. Maybe the implementation on the drone is faulty?
According to the document from the drone, the discovery process is implemented according to mDNS.

**Comment by onovotny** [comment]
Based on my reading of the spec, the drone is wrong. That said, there could be a way to provide an option to query using ANY to get around broken services.

Sent from my Windows 10 phone

**Comment by bberrevoets** [comment]
That would be great, because I can not change the firmware of the drone.
Thanks.

**Comment by onovotny** [comment]
Can you try the latest build in the CI feed:
https://www.myget.org/gallery/zeroconf

Should be `2.9.0-alpha.42` or later.

I've added a `ResolveOptions` and `BrowseDomainsOptions` class to consolidate the parameters go the Resolve/Browse methods. There's a new option there called `ScanQueryType` that defaults to `Ptr`. Can you try setting it to `Any` and see if that works for you?

**Comment by bberrevoets** [comment]
Hi,
I have tested it, works great.
Just one little question. Is it possible to add in the ResolveOptions the possibility to give the Source Port for the broadcast?

**Comment by onovotny** [comment]
I suppose anything is possible, but I'd be curious as to where that's documented? mDNS uses port `5353` as part of the RFC...

**Comment by bberrevoets** [comment]
Yes, you are correct, the queries and the responses go to port 5353, but the query should come from an other port. because if it also come from 5353, there is no response from some services. so it could be a random port.
Below here are 2 screenshots from Wireshark, when the requesting program is working ok.
Screen shot 1 is the request from my program, which gets a reply seen in screen shot 2.
but if I use you library, the source port in screen shot 1 will also be 5353, and there is no response.

Sorry for this explanation, but English is not my native language :)

Greetings Bert.

**Screen shot 1.**

![query](https://cloud.githubusercontent.com/assets/4933105/21583010/9dc19a94-d06d-11e6-9886-b5198cc3ca91.PNG)

**Screen shot 2.**

![response](https://cloud.githubusercontent.com/assets/4933105/21583051/b31fbd98-d06e-11e6-9c9f-3fb61f60e493.PNG)

**Comment by onovotny** [comment]
What platform are you using? What program are you using that generates the working request (and is the source to that available)?

**Comment by bberrevoets** [comment]
I' am using a windows store program called Free Flight 3, and sadly no source code, to generate the working requests. I'm trying to create a library to control the drone. I want to use your library, because that was the only I get results with, when downloading your source code and change the source port some random port number and the PTR to ANY. Free flight is using a different port number every time I start the program.

**Comment by onovotny** [comment]
Okay, so it’s a UWP app. I’ll dig deeper about the source ports.

Where were you making the change to the source port that worked for you?

Sent from my Windows 10 phone

**Comment by bberrevoets** [comment]
I change the port for sending the request to 55555 (nice number :) )
I changed it in a strange place I think, in the file NetworkInterface.cs under Platforms/winrt
the change is on line 97.
I see #if WINDOWS_UWP there, I thought it was there for universal windows, code the code is grayed out.

![capture](https://cloud.githubusercontent.com/assets/4933105/21583714/428e9e54-d08d-11e6-988a-6e50cc74610f.PNG)

Only I don't know where to set the port for listening for the response to port 55555, because listenforAnnouncements are grayed out also.

**Comment by onovotny** [comment]
When I try making that change and using my test app for UWP, it no longer picks up any responses....so not sure how that could be working at all?

What happens when you try the UWP test app project before and after your change? The "Resolve" button in the UI should scan and display all detected devices/services on your network.

the reason it looks greyed out is that the context drop-down in the upper-left of the editor probably isn't set to the UWP version; if you change it, you should get the correct syntax editing.

**Comment by bberrevoets** [comment]
Sorry for the grayed out :) totally forget about it....
If I try your UWP test app, the drone is not responding at all, I can see the printers in the network.
It turns out, that I do not have to change the class from PTR to ANY, only the source port to let the drone responding. But you are right, the UWP test program does not see any responses. That may be because it is listening to responses on port 5353 instead of the port set as source port, because the responses for the services are going to that port now.
But I have to figure it out, how to let your library listen to the source port instead of 5353 :)

Bert

**Comment by onovotny** [comment]
Is this still an issue or can it be closed?
