### ISSUE TITLE
Zeroconf doesn't use or expose TTL

### ISSUE THREAD

**Issue by daveismith** [onovotny/Zeroconf#72]
I'm attempting to write a tool that determines when devices appear and disappear from the network. These devices publish their services by mDNS and when shut down, they send a TTL of 0 for each of the services that are being published. This is the proper behaviour per section 10.1 of rfc6762.

Using ZeroconfResolver.ListenForAnnouncementsAsync() I'm able to see the announcements as they come in. What I do see though is that the announcements are provided to my callback, but they filter out services with a TTL of 0 or pass the details up. Ideally I would like to get the TTL back as part of the service record so that I can easily tell when the service I'm interested in disappears.

To reproduce, you can use Avahi. Starting and stopping the service will generate packets with the appropriate TTL values.

**Comment by onovotny** [comment]
I've just pushed an update that Exposes `Ttl` on each `IService`. It's in `2.9.0-alpha.46` and higher on the CI feed: `https://www.myget.org/F/zeroconf/api/v3/index.json`

Can you please try that and see if it has the expected values? I don't have any easy way of running Avahi.

I'm not explicitly filtering TTL's of 0 (or any other value). I take each response, convert it to a DNS record, match the PTR's to Services and return the results. In this case, I simply hadn't returned the TTL, but I haven't filtered anything.

**Comment by daveismith** [comment]
TTL is showing up now and the values match the values on the wire. Tested on `2.9.0-alpha.48`

**Comment by onovotny** [comment]
Thanks for confirming, I'll get this out into a NuGet release soon.
