### ISSUE TITLE
Get hostname and TXT info

### ISSUE THREAD

**Issue by Matheus-Garbelini** [onovotny/Zeroconf#74]
Hello, I didn't find any example in how to get other information other than host ip. How can i acess information such as host name and TXT info?
I'm using this code:

```C#
responses = await ZeroconfResolver.BrowseDomainsAsync();
```

**Comment by SamihElsakhawi** [comment]
Hi,

is it possible to update your response, because i'm trying to access the txt record from 

`IReadOnlyList<IZeroconfHost> hosts = await ZeroconfResolver.ResolveAsync("_hid._udp.local.", scanTime);`

but it doesn't work.

Than you.
