### ISSUE TITLE
no Automatic Assignment of numeric network addresses in Zeroconf

### ISSUE THREAD

**Issue by LongHoangLe** [onovotny/Zeroconf#76]
one of the big feature Zeroconf is the ability to Automatic Assignment of numeric network addresses, 
but I cant seem to get this feature working ...

here is the setup:  I power up 2 cellPhones: iPhone6 + Samsung 4 Lollipop 5.1 both ran ZeroConfTest 
none of the phone recognized the other ... no interation at all ...

unless I connect both cellPhones to a local router ... 

I ran WiTap on my iPhone6 and iPad, with no router, they can still communicate ... both of these device used zeroconf (Bonjour) Service ... 

so the Zeroconfig is not complete ??? or do I need to include a zeroconf nuget

**Comment by onovotny** [comment]
I'm not sure I understand here -- this Zeroconf library does not currently support service advertisement, only service discovery.
