### ISSUE TITLE
Assembly 'Zeroconf, Version=2.8.0.0' does not have a strong name.

### ISSUE THREAD

**Issue by kakone** [onovotny/Zeroconf#77]
Hello,

The assemblies are not signed in the nuget package. So, we can't use it from our own signed assemblies.
Could you sign the assemblies ?

Cordially,
Stephane.

**Comment by onovotny** [comment]
This would be a breaking change...what is the scenario here? Strong naming does not have any security benefits.

**Comment by kakone** [comment]
It's just for compatibility. Some users sign their desktop assemblies, so they can only reference other strong-named assemblies. And they ask me to sign my assembly (that uses Zeroconf).
I don't think it would be a breaking change (removing a strong-name would be a breaking change), but, finally, I think you are right, it's not a good idea, there will be more inconvenients than benefits.
I will tell the users to read this [article ](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/) :smile:
