### ISSUE TITLE
Exception when port is bound

### ISSUE THREAD

**Issue by joj** [onovotny/Zeroconf#78]
Hi! I'm running into an issue where most of the time I get a "Socket is bound" exception (InvalidOperationException) here: https://github.com/onovotny/Zeroconf/blob/dev/Zeroconf/Platforms/netstandard1.3/NetworkInterface.cs#L92. I have a dozen interfaces (I'm running in windows, with Ethernet and wifi and several vm network connections and bluetooth, etc) and only one or two of those are bound and invalid. The end result is that I get a rethrow of the exception here: https://github.com/onovotny/Zeroconf/blob/dev/Zeroconf/Platforms/netstandard1.3/NetworkInterface.cs#L168 and that invalidates the whole query. 

I added a single "if (client.Client.IsBound) continue;" in line 86 of that file (https://github.com/onovotny/Zeroconf/blob/dev/Zeroconf/Platforms/netstandard1.3/NetworkInterface.cs#L86) and after that everything works beautifully and I get the exact results I'm expecting.

I can send a PR with that but first I wanted to check that that is something that you want. I can also Debug.WriteLine right before continuing so the fact that a socket was bound is kept somewhere. 

Please do tell if that solution is acceptable and I'll send a PR.

Thanks,
joj

**Comment by onovotny** [comment]
@joj Thanks for the report. I'm okay with that fix but it seems strange to me that a check on line 86 would fix it as there hasn't been a connect attempt yet. Is there any way to filter out the unwanted/incompatible adapters earlier in the method?

**Comment by joj** [comment]
@onovotny I think the problem may be (wild guess here) that I actually had a bonjour service (as in, intune bonjour service) running. Either that or an interface (or more than one) was queried several times, not sure. I ended up not doing anything, as the error goes to the OnError in the observable and is not affecting my code, but I do think that that check is not redundant, unless having that in OnError is super important. Also, I might have exaggerated with "most of the time". I do get that _always_ but only on a few interfaces, and as I said I doo have a lot of interfaces :)

**Comment by joj** [comment]
This issue has crept up again. I again fixed on my side, but I want to send a PR anyway. I think the reason for the socket being bound is the retries: an exception _after_ properly binding. When that happens it will happen until retries run out and then the exception will be rethrown. I think my proposed solution is still fine, and it will not change behavior (other than preventing an exception from surfacing). I'll send a PR and you can ignore it or close it if you want :)

**Comment by onovotny** [comment]
Will happily take a PR, thanks!

**Comment by joj** [comment]
Closing this, as it is fixed in https://github.com/onovotny/Zeroconf/pull/83 :)
