### ISSUE TITLE
Fatal signal 11 (SIGSEGV) when build for release

### ISSUE THREAD

**Issue by jmonteschio** [onovotny/Zeroconf#8]
Using Zeroconf in a Xamarin project in Andriod. Works fine when building for debug. However when building for release (and using the "Link SDK Assemblies Only" linker option) Zeroconf gets a SIGSEGV soon after being fired up (looks like during SetSocketOption call).  Stacktrace:

[mono-rt] Stacktrace:
[mono-rt] 
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at (wrapper managed-to-native) System.Net.Sockets.Socket.SetSocketOption_internal (intptr,System.Net.Sockets.SocketOptionLevel,System.Net.Sockets.SocketOptionName,object,byte[],int,int&) <0xffffffff>
[mono-rt]   at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel,System.Net.Sockets.SocketOptionName,object) <0x0017b>
[mono-rt]   at Zeroconf.NetworkInterface/<NetworkRequestAsync>d__1.MoveNext () <0x004bb>
[mono-rt]   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Zeroconf.NetworkInterface/<NetworkRequestAsync>d__1> (Zeroconf.NetworkInterface/<NetworkRequestAsync>d__1&) <0x0004b>
[mono-rt]   at Zeroconf.NetworkInterface.NetworkRequestAsync (byte[],System.TimeSpan,int,int,System.Action`2<string, byte[]>,System.Threading.CancellationToken) <0x00197>
[mono-rt]   at Zeroconf.ZeroconfResolver/<ResolveInternal>d__1.MoveNext () <0x004df>
[mono-rt]   at (wrapper unbox) Zeroconf.ZeroconfResolver/<ResolveInternal>d__1.MoveNext () <0xffffffff>
[mono-rt]   at System.Threading.Tasks.SynchronizationContextContinuation.<Execute>m__0 (object) <0x0003f>
[mono-rt]   at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () <0x00027>
[mono-rt]   at Java.Lang.Thread/RunnableImplementor.Run () <0x0003f>
[mono-rt]   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) <0x0003b>
[mono-rt]   at (wrapper dynamic-method) object.d9fe47de-8f69-4aab-be74-e4bec4c1f295 (intptr,intptr) <0x0003b>
[mono-rt]   at (wrapper native-to-managed) object.d9fe47de-8f69-4aab-be74-e4bec4c1f295 (intptr,intptr) <0xffffffff>
[mono-rt] 
[mono-rt] =================================================================
[mono-rt] Got a SIGSEGV while executing native code. This usually indicates
[mono-rt] a fatal error in the mono runtime or one of the native libraries 
[mono-rt] used by your application.
[mono-rt] =================================================================
[mono-rt] 
[libc] Fatal signal 11 (SIGSEGV) at 0x0000000c (code=1), thread 15082 (kit.Android.dev)

Is there a known way to avoid this problem?

**Comment by jmonteschio** [comment]
BTW, just tried this with your sample "ZeroconfTest.Xam.Anrdriod" Xamarin app. Same thing happens if I build for "Release" and turn on the "Link SDK Assemblies Only" linker option. So it should be something you can reproduce.

**Comment by onovotny** [comment]
There was an issue (bug) with the Xamarin Android linker here:
https://bugzilla.xamarin.com/show_bug.cgi?id=21578

They said it was fixed but I'll reopen it with them.

**Comment by onovotny** [comment]
As a workaround, can you try entering

System;

in to the Ignore Assemblies field in the Project Options->Build->Android Build page

**Comment by onovotny** [comment]
Here's the response I got from Xamarin support:

> It looks like it was fixed in master but was not in any released version. It is noted as being fixed in the preview release of Xamarin Android 5.0 and that preview (UN QA'd and thus unsupported at this time) is available on the web at: http://developer.xamarin.com/guides/android/wear/installation/

>Here are the release notes that show bug 21578 fix as having been included in 5.0: http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.0/

**Comment by jmonteschio** [comment]
Adding "System;" to Ignore Assemblies did indeed fix the issue. Thanks!
