### ISSUE TITLE
Multiple IP addresses (multiple A records) not supported

### ISSUE THREAD

**Issue by jorgensigvardsson** [onovotny/Zeroconf#80]
I am currently working on a fix for this. If this is of interest, a pull request will be available shortly.

**Comment by jorgensigvardsson** [comment]
Please see pull request #81

**Comment by onovotny** [comment]
Closed with https://github.com/onovotny/Zeroconf/commit/cce8c70ca305c466e0110b4d263ebf7787dc830d, thanks!
