### ISSUE TITLE
ZeroConfResolver.ResolveContinuous hangs when no network interfaces are available

### ISSUE THREAD

**Issue by joj** [onovotny/Zeroconf#82]
The repro is fairly simple: do a ResolveContinues and Suscribe on the observable. Then disconnect all network interfaces, and you'll get a lot of extra work going on. This work hangs the parent process. You can see it as a spike of activity in intellitrace. The repro for me is 100%.

**Comment by onovotny** [comment]
Happy to take a PR if you have a chance....

**Comment by joj** [comment]
Sorry, Oren... I switched to using ResolveAsync on a timer, which also lets me check for services being lost. I have my own internal list of discovered services and raise a Found event when I add stuff there, and a Lost event when I remove stuff from there. It works perfectly, except for the fact that zeroconf (in general, not your thing) sometimes will not report active services. My resolution to that is to _not_ take a service out of my list unless I see it disappear 3 times in a row. Perfect for my needs. For that code I can send a PR if you want to add a new api artifact that works on events instead of the observable.

**Comment by onovotny** [comment]
Would definitely love to see what you've come up with. Having a list of "current" items sounds like a generally useful thing!

**Comment by onovotny** [comment]
@joj I'd like to get 2.9 out very soon with the other fix you had. If you can send a PR that includes this too, I can include it there.

**Comment by joj** [comment]
I'll have some time for this during the weekend. I can't move my code directly but need to rewrite it instead. I will, but not just now. Is that good enough for you? Go ahead with 2.9 if it's not and we'll include it in the next version.

**Comment by onovotny** [comment]
I can wait until after the weekend, the current version is on the MyGet feed to unblock people otherwise.
Thanks!

**Comment by onovotny** [comment]
v 2.9 is out on NuGet; thanks for your PR and would love to see the docs when you get a chance!
