### ISSUE TITLE
ResponseToZeroConf is only returning the first address

### ISSUE THREAD

**Issue by joj** [onovotny/Zeroconf#87]
Hey, Oren. If I'm not reading this incorrectly: https://github.com/onovotny/Zeroconf/blob/dev/Zeroconf/ZeroconfResolver.cs#L86, you're getting the first result from the response and discarding the rest. From what I understand about the protocol the proper way of implementing this should be to return all the discovered addresses for a single record, and then the user should try to connect with each one of them until one works. This is specially important in mac/parallels scenarios (we have a lot of those) where the first address in parallels is usually a local address, and the second or third is the mac (which is the address we need).

Changing this may be braking, though, at least semantically. IZeroConf should have a list of IPAddresses and not just the one. The way to make it non-breaking would be to leave IPAddress as the first one, but also provide the list. Are you ok with that change?

**Comment by onovotny** [comment]
That should be returning all addresses in that list... selecting the A records, and the additional A records and taking a distinct list. Where do you see it being dropped?

**Comment by joj** [comment]
There's a FirstOrDefault in there.

**Comment by joj** [comment]
Wait, my code is different. Checking. Maybe that was changed and I just need to update.

**Comment by joj** [comment]
Yep, nevermind this issue. I have to update. That was already resolved :)

**Comment by onovotny** [comment]
Was implemented in this PR https://github.com/onovotny/Zeroconf/pull/81
