### ISSUE TITLE
Unable to get txt records

### ISSUE THREAD

**Issue by jdrobert** [onovotny/Zeroconf#9]
Hello,

Thanks for working on this package. It has been a breeze to get setup. The only problem I'm running into is that the TXT records I'm looking for aren't coming through. Zeroconf will find the host I'm looking for and its IP but the services dictionary is always empty. 

Here is the code that I am using.
```c#
public async Task StartDiscovery()
 {
    Action<IZeroconfHost> callback = new Action<IZeroconfHost>((IZeroconfHost host) => 
    {
        Debug.WriteLine(host.Services.Count); 
    });

    IReadOnlyList<IZeroconfHost> results = 
        await ZeroconfResolver.ResolveAsync(SERVICE_TYPE, new TimeSpan(0, 0, 10), 4, 2000, callback);
    Debug.WriteLine(results);
}
```

This is what I see when hitting my breakpoint in the callback. 
![vs-01](https://cloud.githubusercontent.com/assets/5350419/7101987/88533ec4-e037-11e4-8aaa-c4fe173d2372.png)

I used an app called All My LAN and it finds the device and all properties. 
![all_lan](https://cloud.githubusercontent.com/assets/5350419/7101988/8859230c-e037-11e4-88f6-087c81571746.png)

Am I doing anything wrong? I'd really appreciate any help you could provide. Thanks!

**Comment by jdrobert** [comment]
I pulled the shared/RT code into my app and I think I've figured it out. 

In ZeroconfResolver.cs, when I change Additionals to Answers I get the txt records for my service. Is there a way this can be done automatically?

ZeroconfResolver.cs line 249
```C#
// Get the matching service records
var serviceRecords = response.Answers
    .Where(r => r.NAME == ptrRec.PTRDNAME)
    .Select(r => r.RECORD)
    .ToList();
```

**Comment by onovotny** [comment]
I'll take a look, I thought there was a reason I was using one of them and not the other. Actually, what happens if you union/distinct the answers and additional making sure there are no dups? That might be the best solution.

**Comment by jdrobert** [comment]
This seems to work for me. 

```C#
List<RR> resourceRecords = new List<RR>().Union(response.Answers).Union(response.Additionals).ToList();
// Get the matching service records
var serviceRecords = resourceRecords
    .Where(r => r.NAME == ptrRec.PTRDNAME)
    .Select(r => r.RECORD)
    .ToList();
```

Thanks! This helps me out a lot!

**Comment by jmonteschio** [comment]
Would love to see this go into the xamarin android package. Right now I'm only bringing the package into my project (not the source code) and would rather keep it that way. Being able to reliably get to the TXT info would make my app much nicer.  Currently I have to communicate with the device to find out what's already being made available through the TXT info.

**Comment by jdrobert** [comment]
@jmonteschio I don't feel comfortable submitting a PR because I can only test in WP8.1 but I can create a fork and include this change. Would you be interested in testing it?

I've never done it before but it looks like you can create a local NuGet package and install it. 
https://blogs.endjin.com/2014/07/how-to-test-nuget-packages-locally/

**Comment by jmonteschio** [comment]
Thanks for the ideas. I can’t commit to testing it right now but if time permits I can probably temporarily bring in the source and then test your change. I just don’t want to manage the source code in my project on a long-term basis.

Ultimately I’d like to see txt records working in zerconf in Android. :)


The Enphase System | Empowering Solar Technology



On Apr 14, 2015, at 6:19 AM, jdrobert <notifications@github.com> wrote:

> @jmonteschio I don't feel comfortable submitting a PR because I can only test in WP8.1 but I can create a fork and include this change. Would you be interested in testing it?
> 
> I've never done it before but it looks like you can create a local NuGet package and install it. 
> https://blogs.endjin.com/2014/07/how-to-test-nuget-packages-locally/
> 
> —
> Reply to this email directly or view it on GitHub.
> 




This email message is for the sole use of the intended recipient(s) and may contain confidential and/or privileged information. If you are not an intended recipient, you may not review, use, copy, disclose or distribute this message. If you received this message in error, please contact the sender by reply email and destroy all copies of the original message.

**Comment by jdrobert** [comment]
You wouldn't need to pull the source into your project. You'd clone my repo, follow the instructions in the link I sent and install it as a local NuGet package.

**Comment by onovotny** [comment]
I've put these changes into 2.3.3, now on NuGet. Please let me know if that works for you.

**Comment by jmonteschio** [comment]
Yes, I was finally able to test this on Xamarin/Android, and it worked!

- John

The Enphase System | Empowering Solar Technology



On Apr 16, 2015, at 10:04 AM, Oren Novotny <notifications@github.com> wrote:

> I've put these changes into 2.3.3, now on NuGet. Please let me know if that works for you.
> 
> —
> Reply to this email directly or view it on GitHub.
> 




This email message is for the sole use of the intended recipient(s) and may contain confidential and/or privileged information. If you are not an intended recipient, you may not review, use, copy, disclose or distribute this message. If you received this message in error, please contact the sender by reply email and destroy all copies of the original message.
