### ISSUE TITLE
FileNotFoundException System.Reactive.Linq

### ISSUE THREAD

**Issue by matthew-a-thomas** [onovotny/Zeroconf#98]
I get this error message:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.
  at at Zeroconf.ZeroconfResolver.Resolve(ResolveOptions options)
  at at Zeroconf.ZeroconfResolver.Resolve(IEnumerable`1 protocols, TimeSpan scanTime, Int32 retries, Int32 retryDelayMilliseconds)
  at at Zeroconf.ZeroconfResolver.Resolve(String protocol, TimeSpan scanTime, Int32 retries, Int32 retryDelayMilliseconds)
```

It's a totally fresh .Net Core project. Here's my code:

```csharp
using (ZeroconfResolver.Resolve("_http._tcp.local.").Subscribe(Display))
{
    Console.ReadKey(true);
}
```

The `Display` method just does a bunch of `Console.WriteLine`.

If I reference the `System.Reactive.Linq` Nuget package then the error goes away. But I don't need that package in my project.

Is the `Zeroconf` package missing a package dependency?

**Comment by onovotny** [comment]
Hi,

This is a case where Zeroconf is still using Rx 3.x and I'm guessing you're using Rx.NET 4.x. That's documented here https://github.com/dotnet/reactive#v40-changes where there's a compatibility package to enable libraries compiled against 3.x to work with 4.x.

**Comment by matthew-a-thomas** [comment]
> I'm guessing you're using Rx.NET 4.x

That's correct, I'm using `System.Reactive` 4.0.0. Thanks for linking to the compatibility shim.

> Zeroconf is still using Rx 3.x

Any plans to depend on `System.Reactive` >= 4.0.0?

**Comment by onovotny** [comment]
Version 3.0 will depend on Rx4, the MyGet feed has this already. Should be published to NuGet soon.

**Comment by onovotny** [comment]
publishing today
