### ISSUE TITLE
Observable publishes duplicates of all `IZeroconfHost` objects

### ISSUE THREAD

**Issue by matthew-a-thomas** [onovotny/Zeroconf#99]
# Description
Two of every host object gets published through the `Resolve` method's `Observable` sequence. The `IZeroconfHost` objects have identical hash codes.

They do not have identical `Services` dictionary instances (the dictionaries have different hash codes). Also, the `Service` dictionaries do not contain identical `IService` instances (the instances have different hash codes).

However, the `IService` instances in the `Services` of the duplicated `IZeroconfHost` objects contain identical information.

In summary, the same `IZeroconfHost` object gets published twice with the same information, just with different service dictionary instances.

# Duplicate `IZeroconfHost` object instances
## Code
```csharp
using System;
using Zeroconf;

class Program
{
    static void Main()
    {
        using (ZeroconfResolver.Resolve("_http._tcp.local.")
            .Subscribe(x => Console.WriteLine(x.GetHashCode())))
        {
            Console.ReadKey(true);
        }
    }
}
```

## Output
```
-809780704
-809780704
-958303524
-958303524
1270891396
1270891396
327121424
327121424
(etc)
```

# Duplicate service description content
## Code
```csharp
using System;
using System.Security.Cryptography;
using Zeroconf;

class Program
{
    static readonly int Salt;

    static Program()
    {
        var saltBytes = new byte[4];
        using (var cng = RandomNumberGenerator.Create())
            cng.GetBytes(saltBytes);
        Salt = BitConverter.ToInt32(saltBytes);
    }

    static void Main()
    {
        using (ZeroconfResolver.Resolve("_http._tcp.local.")
            .Subscribe(Display))
        {
            Console.ReadKey(true);
        }
    }

    static void Display(
        IZeroconfHost host)
    {
        Console.WriteLine(host.GetHashCode());
        foreach (var service in host.Services.Values)
        {
            Console.WriteLine($"\t{(service.Name.GetHashCode() + Salt)} (salted port {(service.Port + Salt)})");
        }
    }
}
```

Note that I don't want to reveal network configuration details to the whole world through this GitHub issue. Hence the `Salt`.

## Output
```
-309800500
        -300658212 (salted port 772093928)
-309800500
        -300658212 (salted port 772093928)
677414424
        -300658212 (salted port 772090426)
677414424
        -300658212 (salted port 772090426)
(etc)
```

**Comment by onovotny** [comment]
Can you try the latest `v3.0.0-build.26` on the MyGet feed? I just fixed an issue that may be related where other network devices sometimes echo services. Those echos are now filtered out.

**Comment by matthew-a-thomas** [comment]
@onovotny Looks like `v3.0.0-build.26` on the MyGet feed doesn't have this issue.

**Comment by onovotny** [comment]
Thanks for the confirm, I'll aim to get this out asap, in the next day or two.

**Comment by onovotny** [comment]
Publishing v3 to nuget.org today
